### ISSUE TITLE
Upgrade project to .NET 6

### ISSUE THREAD

**Issue by LRScudeletti** [fenomeno83/SwaggerGlobalization#2]
Hello my friend.

Your project is very good, you could update it to be compatible with .NET 6.

Thanks in advance.

Hug.

**Comment by fenomeno83** [comment]
Hi.

I've upgraded to .net 6

**Comment by LRScudeletti** [comment]
Hi.

My .NET 6 project doesn't have the Startup.cs class. So I was unable to implement this solution.

**Comment by fenomeno83** [comment]
I've fixed some bugs in new push made now

Sorry, I suggest you to try new pushed version and try to integrate files/line codes in your solution.
Or undestand how to move Startup code to your solution

**Comment by fenomeno83** [comment]
here there is example to migrate 5.0 to 6.0 combining startup.cs+program.cs in program.cs (in this case framework is already 6.0, but you need this example guide only to move my startup.cs code into program.cs)

https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-7.0&tabs=visual-studio

**Comment by fenomeno83** [comment]
see also here

https://andrewlock.net/exploring-dotnet-6-part-12-upgrading-a-dotnet-5-startup-based-app-to-dotnet-6/

**Comment by fenomeno83** [comment]
Hi @LRScudeletti 
I've merged Startup into Program.cs (and removed Startup) like new microsoft templates
