### ISSUE TITLE
When running the application in IISExpress, the .js scripts are not loaded.

### ISSUE THREAD

**Issue by LRScudeletti** [fenomeno83/SwaggerGlobalization#3]
Hello!

When running the application in IISExpress, the .js scripts are not loaded. I already tried using the always copy option and also the embedded resource option but it always gives me the below error:

- Failed to load resource: the server responded with a status of 404 () translate.js:1 
- Failed to load resource: the server responded with a status of 404 () jquery.initialize.min.js:1
- Failed to load resource: the server responded with a status of 404 () jquery-3.3.1.min.js:1 

The project has no changes, it is exactly the same as the repository. Do you have any idea why this happens?

Thanks.

**Comment by fenomeno83** [comment]
Hi. If you use IIS, you need to modify web.config in root of your deployed application

This should be work. For example

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <location path="." inheritInChildApplications="false">
        <system.webServer>
          <handlers>
            <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
          </handlers>
          <aspNetCore processPath="dotnet" arguments=".\SwaggerGlobalization.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
        </system.webServer>
      </location>
      <system.webServer>
        <security>
           <requestFiltering>
             <verbs>
              <clear />
            </verbs>
          </requestFiltering>
        </security>
      </system.webServer>
    </configuration>
    

try to add the second system.webserver node in your auto generated iis webconfig

if you use iisexpress it should be work without anything. But try to add complete web.config as my example  in your your solution, at project level (the same of appsettings.json)

**Comment by fenomeno83** [comment]
if it doesn't work try also this in webconfig

    <system.webServer>  
        <staticContent>
          <remove fileExtension=".js" />
          <mimeMap fileExtension=".js" mimeType="text/javascript" />
        </staticContent>	
    <system.webServer>

**Comment by fenomeno83** [comment]
this could be a complete web.config

    <?xml version="1.0" encoding="utf-8"?>
     <configuration>
      <location path="." inheritInChildApplications="false">
        <system.webServer>
          <handlers>
            <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
          </handlers>
          <aspNetCore processPath="dotnet" arguments=".\SwaggerGlobalization.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
        </system.webServer>
      </location>
      <system.webServer>
        <security>
           <requestFiltering>
             <verbs>
              <clear />
            </verbs>
          </requestFiltering>
        </security>
        <staticContent>
          <remove fileExtension=".js" />
          <mimeMap fileExtension=".js" mimeType="text/javascript" />
        </staticContent>
      </system.webServer>
    </configuration>

**Comment by LRScudeletti** [comment]
Hi. It worked following his instructions. Thanks.

**Comment by fenomeno83** [comment]
Hi @LRScudeletti  just to understand, what mine istructions are you used to get js working in swagger?

**Comment by LRScudeletti** [comment]
> Hi @LRScudeletti just to understand, what mine istructions are you used to get js working in swagger?

It worked when I added a complete web.config.
