### ISSUE TITLE
When an error occurs on the endpoint, Swagger only displays the error in English.

### ISSUE THREAD

**Issue by LRScudeletti** [fenomeno83/SwaggerGlobalization#5]
Hi

When an error occurs on my endpoint, Swagger displays an error in English, for example:
Error: Response status is 404.

Shouldn't Swagger display the message configured on my controller? For example:

`/// <response code="404">swagger_response_404</response>`

Resource-es:
swagger_response_404 = No se encontró información.

**Comment by fenomeno83** [comment]
Hi.
That message is only for response documentation (tag description under specific response code) before that you execute your api, not for error message on effective response after execution (note also that if you want show a different output response model (against default 200 output model) in swagger documentation, you need to decorate your api method for example with

 ................    
   
         /// <response code="404">swagger_response_404</response>
.............

        [ProducesResponseType(404, Type = typeof(BaseResponse))]
        public async Task<ActionResult<TestResponse>> Update(TestRequest request, [FromRoute] int id)

If you want change that message, you can do client side, for example, add this in translate.js

      $.initialize('.renderedMarkdown > p', function () {
        if ($(this).html().startsWith("Error: response status is")) {
            $(this).html($(this).html().replace("Error: response status is", resource_globalization["ResponseStatusId"]));

        }
    });

than add localization for ResponseStatusId in localizatio json, for example

en.js
       "ResponseStatusId": "Error: response status is"

it.js
         "ResponseStatusId": "Errore: il codice risposta &egrave;"

**Comment by fenomeno83** [comment]
I've pushed a new version with fixes

**Comment by LRScudeletti** [comment]
Hi. 

I followed your suggestion to change it on the client side and it worked great.

Thanks.
